[platformio]
default_envs = main

[env]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    adafruit/Adafruit BME680 Library
    https://github.com/DFRobot/DFRobot_HumanDetection.git
    knolleary/PubSubClient
    bblanchon/ArduinoJson
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DMQTT_MAX_PACKET_SIZE=2048

[env:main]
build_src_filter = +<main.cpp> -<sensor_test.cpp>

[env:sensor_test]
build_src_filter = +<sensor_test.cpp> -<main.cpp>
